import { UserRole, Priority, KanbanStatus, EquipmentStatus } from '../types';

export const mockUsers = [
  { id: '1', name: 'Admin User', email: 'admin@example.com', role: UserRole.ADMIN },
  { id: '2', name: 'John Technician', email: 'john@example.com', role: UserRole.TECHNICIAN },
  { id: '3', name: 'Jane Technician', email: 'jane@example.com', role: UserRole.TECHNICIAN },
  { id: '4', name: 'Regular User', email: 'user@example.com', role: UserRole.USER },
];

export const mockEquipment = [
  {
    id: '1',
    name: 'HVAC Unit #001',
    category: 'HVAC',
    location: 'Building A - Floor 2',
    status: EquipmentStatus.ACTIVE,
    description: 'Main air conditioning unit for second floor',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Elevator #002',
    category: 'Elevator',
    location: 'Building A - Main',
    status: EquipmentStatus.ACTIVE,
    description: 'Main passenger elevator',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '3',
    name: 'Generator #003',
    category: 'Power',
    location: 'Building A - Basement',
    status: EquipmentStatus.UNDER_MAINTENANCE,
    description: 'Backup power generator',
    createdAt: '2024-01-05T12:00:00Z',
    updatedAt: '2024-01-20T14:00:00Z',
  },
  {
    id: '4',
    name: 'Water Pump #004',
    category: 'Plumbing',
    location: 'Building B - Basement',
    status: EquipmentStatus.ACTIVE,
    description: 'Main water circulation pump',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
  },
];

export const mockRequests = [
  {
    id: '1',
    equipmentId: '1',
    equipment: mockEquipment[0],
    issueDescription: 'AC unit not cooling properly, temperature remains high',
    priority: Priority.HIGH,
    status: KanbanStatus.IN_PROGRESS,
    assignedTechnicianId: '2',
    assignedTechnician: mockUsers[1],
    requestDate: '2024-01-25T09:00:00Z',
    attachments: [],
    comments: [
      {
        id: '1',
        requestId: '1',
        userId: '2',
        userName: 'John Technician',
        content: 'Inspected unit, found refrigerant leak. Ordering parts.',
        createdAt: '2024-01-25T14:30:00Z',
      },
    ],
    createdAt: '2024-01-25T09:00:00Z',
    updatedAt: '2024-01-25T14:30:00Z',
  },
  {
    id: '2',
    equipmentId: '2',
    equipment: mockEquipment[1],
    issueDescription: 'Elevator making unusual noise on descent',
    priority: Priority.MEDIUM,
    status: KanbanStatus.ASSIGNED,
    assignedTechnicianId: '3',
    assignedTechnician: mockUsers[2],
    requestDate: '2024-01-26T10:00:00Z',
    attachments: [],
    comments: [],
    createdAt: '2024-01-26T10:00:00Z',
    updatedAt: '2024-01-26T11:00:00Z',
  },
  {
    id: '3',
    equipmentId: '3',
    equipment: mockEquipment[2],
    issueDescription: 'Generator failed during power outage test',
    priority: Priority.CRITICAL,
    status: KanbanStatus.UNDER_REVIEW,
    assignedTechnicianId: '2',
    assignedTechnician: mockUsers[1],
    requestDate: '2024-01-20T08:00:00Z',
    attachments: [],
    comments: [
      {
        id: '2',
        requestId: '3',
        userId: '2',
        userName: 'John Technician',
        content: 'Replaced faulty starter motor. Generator now operational.',
        createdAt: '2024-01-24T16:00:00Z',
      },
    ],
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-24T16:00:00Z',
  },
  {
    id: '4',
    equipmentId: '4',
    equipment: mockEquipment[3],
    issueDescription: 'Water pump leaking from seal',
    priority: Priority.MEDIUM,
    status: KanbanStatus.NEW,
    assignedTechnicianId: null,
    assignedTechnician: null,
    requestDate: '2024-01-27T11:00:00Z',
    attachments: [],
    comments: [],
    createdAt: '2024-01-27T11:00:00Z',
    updatedAt: '2024-01-27T11:00:00Z',
  },
  {
    id: '5',
    equipmentId: '1',
    equipment: mockEquipment[0],
    issueDescription: 'Routine maintenance check completed',
    priority: Priority.LOW,
    status: KanbanStatus.COMPLETED,
    assignedTechnicianId: '3',
    assignedTechnician: mockUsers[2],
    requestDate: '2024-01-15T09:00:00Z',
    attachments: [],
    comments: [
      {
        id: '3',
        requestId: '5',
        userId: '3',
        userName: 'Jane Technician',
        content: 'Completed routine maintenance. All systems functioning normally.',
        createdAt: '2024-01-15T15:00:00Z',
      },
    ],
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-15T15:00:00Z',
  },
];

